title: Haotian Huang's Portfolio
email: haotianhuang142@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Haotian Huang's personal portfolio. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Hunghotin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Haotian Huang # add your name
author-pic: # adam-face.jpg
about-author: 我是来自北京大学的黄浩天，主修地球化学与经济学。我对探索地球与市场的内在规律充满热情，并致力于在量化金融领域运用数据科学解决复杂问题。在代码和模型之外，我热爱篮球、滑雪和摄影，享受运动带来的挑战与生活中的美好瞬间。

# Contact links
email: haotianhuang142@gmail.com # Add your Email address
phone: (86)131-7887-8206 # Add your Phone number
website: # Add your website, do not add http://
linkedin: haotian-huang447 # Add your Linkedin handle
wechat: # Add your wechat username or QR code image name
github: Hunghotin # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
